name: CMake

on:
  push:
    branches: [ main ]

env:
  BUILD_TYPE: Debug # builds faster

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
    - uses: actions/setup-node@v2.4.1
      with:
        node-version: 14.x
    - name: Setup Node
      run: cd extern/bstruct && npm i
    
    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

    - name: Create Release Zip
      run: |
        mkdir primewatch2
        cp build/* primewatch2/
        dir /s primewatch2
        tar -a -c -f primewatch2.zip -R primewatch2

    - name: upload
      uses: actions/upload-artifact@v2.2.4
      with:
        name: primewatch2
        path: primewatch2.zip
        if-no-files-found: error
