name: CMake

on:
  push:
    branches: [ main ]
    tags:
      - 'v[0-9]+.*'

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: stable

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - name: Build
      run: |
        cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

    - name: Create Release Zip
      run: |
        mkdir primewatch2
        cp -r prime_defs/ primewatch2/
        cp build/${{env.BUILD_TYPE}}/primewatch2.exe primewatch2/
        tar -a -c -f primewatch2.zip primewatch2

    - name: Upload Arifacts
      uses: actions/upload-artifact@v3
      with:
        name: primewatch2
        path: primewatch2/**
        if-no-files-found: error

    - name: Create Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/v')
      with:
        files: primewatch2.zip
        body: Automated release build
